language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
  - nightly

before_script:
  # Install graphviz for the creation of the documentation
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpdoc run -d Classes/ -t doc/

after_success:
  # Only push the documentation to the gh-pages if this is no pull request,
  # it is the master branch and it is build with PHP 5.6
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $(php -v | grep 'PHP 5' | sed 's/.*PHP \([^-]*\).*/\1/' | cut -c 1-3) == "5.6" && bash gh-pages.sh

env:
  global:
    - secure: "b6jc5t3ZEb9OfO5vzbXr53OA6NZ27qXrVQddblki0R8Twr8BzfvYmttwGbjT+nXHtQ9P4DXUgGuQcNdKhHGbo8iS7BpHH9i14Ngw7MqNST+iw9Vw6eZ5254g1wPDPCbIODdPw48P6lSvDN/wULW4ASP60z/3MN7+L0Qrm8cQyiLx4nGciO9Fg0NAu7tyIcdXvXWFw7DZlPU4ZjXJOenomXbchOrtiegZikb2XrCF+DUpiCjTxunynUkH10GnxvknabTmfkHdnm2TpPbSPT433N2X7c7oUWSjUJ4tq5BmLty5AVB10AMbbIDkjQGBn8P03L4ZDNRMCAGn2xsW0QzScV0e4De5m00UzJinQAPAOz1UNUIiIl5VERp1bts2BFdUZxloTF1tO725U2Ey4RYnk2z77+0vfh+Xevw8oN3dDcsGBnCHDGc6/4vD5JgFs+RerQpvpouOAAdm0Xm7XTPQGK5D+a1TwphfJ/UQYzyN1boxXys+tE3HzYHisTBVvau2WHqYJCVsrC/XPw94H5B9k0QzA/GNoQFHFNJcYCVB2MuXRgq2EiFAjqnSNHqFATCp7EueyNcrueF42EolR7OFh+Jf18q6MEILtW+aecqMxIvZ28AVkH4EY7KeLekKOmpQ11zObc+BMir3uzOIDd9qafm9r21YQwMa3Zuu+vElvbo="
